orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  test_echo:
    docker:
      - image: 'cimg/node:lts-browsers'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: node --version
      - run: echo 'Hello World!'
  list_cmd:
    docker:
      - image: 'cimg/node:lts'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: List Avaiable commands
          command: ls -al
      - run: echo 'Above are available commands'
workflows:
  app_tests:
    jobs:
      - test_echo
      - node/test:
          requires:
            - test_echo
  list_stuff:
    jobs:
      - list_cmd
