orbs: # declare what orbs we are going to use
  node: circleci/node@4.1.0 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  test_echo:
    docker:
      - image: 'cimg/node:lts-browsers'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: node --version
      - checkout
      - run: ls -a
      - store_artifacts:
          path: README.md
      - run: echo 'Hello World!'

workflows:
  app_tests:
    jobs:
      - test_echo
